### ISSUE TITLE
Is there the same app on other platform?

### ISSUE THREAD

**Issue by b3326023** [antocreo/BYO_Master#1]
Is there the same app on other platform?
Like Windows or Android....
Because I don't have either MacOS nor iOS....
Please!

**Comment by antocreo** [comment]
Hi,
I developed it only for OSX. Depending on your level of skills, if you use VisualStudio and OF for VS, I am pretty sure you can port it to Windows. Actually, if you do it, let me know.
Sorry I can't help further

**Comment by b3326023** [comment]
Thnak you!I will try it,I am just using Visual Studio. And excuse me,what
is "OF" you mentioned?
And "VS" means  Visual Studio?

2017年2月12日 23:33，"Anto" <notifications@github.com>寫道：

Hi,
I developed it only for OSX. Depending on your level of skills, if you use
VisualStudio and OF for VS, I am pretty sure you can port it to Windows.
Actually, if you do it, let me know.
Sorry I can't help further

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/antocreo/BYO_Master/issues/1#issuecomment-279226134>,
or mute the thread

**Comment by antocreo** [comment]
OF [Openframeworks] http://openframeworks.cc/
I am using this to develop the app. You will need to install it for VS (Visual Studio) as well as the dependencies addons.
I don't know much about OF for Windows, but the OF community is quite big and very helpful. I recommend to rely on their forum if you need help with it.
cheers

**Comment by b3326023** [comment]
OK!
Thanks very much!

2017-02-12 23:54 GMT+08:00 Anto <notifications@github.com>:
